Improve deploy on homolog

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy Flutter Web Build
+name: Production Flutter Web Build
 
 on:
   push:
@@ -8,10 +8,15 @@ env:
   project: monitor-geral-p8
   folder: production
   version: ""
+  flutter_version: '3.0.1'
+  labs_path: C:\labs
+  rollback_by_commit: ${{ secrets.rollback_by_commit }}
+  project_url: 'https://monitorgeral.carajaslabs.com.br'
+  nginx_folder: server
 
 jobs:
   build:
-    runs-on: self-hosted
+    runs-on: [ self-hosted, Windows, production ]
     steps:
       - uses: actions/checkout@v3
         with:
@@ -19,31 +24,114 @@ jobs:
           clean: false
       - uses: joeserhtf/flutter-action@main
         with:
-          flutter-version: '3.0.1'
+          flutter-version: ${{ env.flutter_version }}
       - name: Go to folder fetch data and build
         run: |
           cd ${{ env.folder }}
           flutter clean
           flutter pub get
           flutter build web
-          echo "${{ env.project }}"
-        # Problems with bash on windows .sh from flutter default
-        # make jq
 
   deploy:
     needs: build
-    runs-on: self-hosted
+    runs-on: [ self-hosted, Windows, production ]
     steps:
+      - name: Make backup
+        run: |
+          if (Test-Path -Path ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }}) {
+            XCOPY ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }} ${{ env.labs_path }}\${{ env.folder }}\backup\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }} /D /E /Y /I
+          } else {
+            echo "First deploy no backup available"
+          }
       - name: Copy last update
-        run: XCOPY ${{ github.workspace }}\${{ env.folder }}\build\web C:\labs\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }} /D /E /Y /I
+        run: |
+          XCOPY ${{ github.workspace }}\${{ env.folder }}\build\web ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }} /D /E /Y /I
+          XCOPY ${{ github.workspace }}\${{ env.folder }}\location_config ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }}\location_config /D /E /Y /I
 
   location:
     needs: deploy
-    runs-on: self-hosted
+    runs-on: [ self-hosted, Windows, production ]
     steps:
+      - name: Backup of Nginx location folder
+        run: |
+          if (Test-Path -Path ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\${{ env.nginx_folder }}s) {
+            XCOPY ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\${{ env.nginx_folder }}s ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\backup\${{ env.nginx_folder }}s /D /E /Y /I
+          } else {
+            echo "First deploy, no backup available for nginx"
+          }
       - name: Copy server nginx
-        run: XCOPY ${{ github.workspace }}\${{ env.folder }}\location_config\${{ env.project }}${{ env.version != '' && '_' || '' }}${{ env.version }}_server.conf C:\labs\production\nginx_labs\labs\servers\ /D /Y /I
+        run: |
+          if (Test-Path -Path ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }}\location_config\${{ env.project }}${{ env.version != '' && '_' || '' }}${{ env.version }}_${{ env.nginx_folder }}.conf) {
+            XCOPY ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }}\location_config\${{ env.project }}${{ env.version != '' && '_' || '' }}${{ env.version }}_${{ env.nginx_folder }}.conf ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\${{ env.nginx_folder }}s\ /D /E /Y /I
+          } else {
+            echo Location file not found ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }}\location_config\${{ env.project }}${{ env.version != '' && '_' || '' }}${{ env.version }}_${{ env.nginx_folder }}.conf
+          }
       - name: Reload Nginx
         run: |
-          cd C:\labs\production\nginx_labs
+          cd ${{ env.labs_path }}\${{ env.folder }}\nginx_labs
           .\nginx -s reload
+
+  rollback:
+    needs: [ build, deploy, location ]
+    runs-on: [ self-hosted, Windows, production ]
+    if: always() && ( needs.deploy.result == 'failure' || needs.location.result == 'failure' )
+    steps:
+      - name: Set up token
+        if: ${{ env.rollback_by_commit == 'true' }}
+        uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.ACTIONS_TOKEN }}
+          path: ${{ github.workspace }}\${{ env.folder }}
+          clean: false
+      - name: Backup from old commit
+        if: ${{ env.rollback_by_commit == 'true' }}
+        run: |
+          cd ${{ env.folder }}
+          git push --force origin ${{ github.event.before }}:${{ env.folder }}
+      - name: Copy backup from folder
+        if: ${{ env.rollback_by_commit != 'true' }}
+        run: |
+          XCOPY ${{ env.labs_path }}\${{ env.folder }}\backup\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }} ${{ env.labs_path }}\${{ env.folder }}\apps\${{ env.project }}${{ env.version != '' && '\' || '' }}${{ env.version }} /D /E /Y /I
+      - name: Backup nginx to remove wrong config
+        if: ${{ env.rollback_by_commit != 'true' && needs.location.result == 'failure' }}
+        run:
+          if (Test-Path -Path ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\${{ env.nginx_folder }}s\${{ env.project }}${{ env.version != '' && '_' || '' }}${{ env.version }}_${{ env.nginx_folder }}.conf) {
+            Remove-item ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\${{ env.nginx_folder }}s\${{ env.project }}${{ env.version != '' && '_' || '' }}${{ env.version }}_${{ env.nginx_folder }}.conf -Recurse -Force -Confirm:$false
+            XCOPY ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\backup\${{ env.nginx_folder }}s ${{ env.labs_path }}\${{ env.folder }}\nginx_labs\labs\${{ env.nginx_folder }}s /D /E /Y /I
+            cd ${{ env.labs_path }}\${{ env.folder }}\nginx_labs
+            .\nginx -s reload
+          } else {
+            echo "No config found that caused error"
+          }
+
+  send_telegram_notification:
+    runs-on: ubuntu-latest
+    needs: [ build, deploy, location, rollback ]
+    if: always()
+    steps:
+      - name: Send telegram message end
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TELEGRAM_TO }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          message: |
+            ${{ env.folder == 'production' && '⚠ Production' || 'Homolog' }} deploy completed with: ${{ (needs.build.result == 'success' && needs.deploy.result == 'success' && needs.location.result == 'success') && ' ✅ Success' || ' ❌ Failure' }}
+
+            Url: ${{ env.project_url }}
+
+            Repository: ${{ github.repository }}
+            ${{ github.actor }} created commit to branch: ${{ github.ref_name }}:
+            Commit message: ${{ github.event.commits[0].message == '' && 'Rollback from break' || github.event.commits[0].message }}
+
+            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
+
+            See Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+
+            ${{ needs.rollback.result == 'skipped' && format('See previous commit: https://github.com/{0}/commit/{1}', github.repository, github.event.before) || ( secrets.rollback_by_commit == 'true' && format('RollBack to: https://github.com/{0}/commit/{1}', github.repository, github.event.before) || 'RollBack made from folder' ) }}
+            ${{ needs.rollback.result == 'skipped' && ' ' || ( needs.rollback.result == 'success' && ( secrets.rollback_by_commit == 'true' && format('✅ RollBack iniciado com sucesso no commit: {0} workflow em execução', github.event.before) || '✅ RollBack realizado com sucesso' ) || '❌ Error ao realizar rollback' ) }}
+
+            Jobs:
+              Build: ${{ needs.build.result == 'success' && ' 🟢 Success' || ( needs.build.result == 'failure' && ' 🔴 Failure' || ( needs.build.result == 'skipped' && ' ⚪ Skipped' || ' 🟠 Cancelled' ) ) }}
+              Deploy: ${{ needs.deploy.result == 'success' && ' 🟢 Success' || ( needs.deploy.result == 'failure' && ' 🔴 Failure' || ( needs.deploy.result == 'skipped' && ' ⚪ Skipped' || ' 🟠 Cancelled' ) ) }}
+              Location: ${{ needs.location.result == 'success' && ' 🟢 Success' || ( needs.location.result == 'failure' && ' 🔴 Failure' || ( needs.location.result == 'skipped' && ' ⚪ Skipped' || ' 🟠 Cancelled' ) ) }}
+              Rollback: ${{ needs.rollback.result == 'success' && ' 🟢 Success' || ( needs.rollback.result == 'failure' && ' 🔴 Failure' || ( needs.rollback.result == 'skipped' && ' ⚪ Skipped' || ' 🟠 Cancelled' ) ) }}
